[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
xflags = "0.3.2"
anyhow = "1.0.0"
xshell = "*"
ungrammar = "*"
either = "*"
proc-macro2 = "1.0.94"
quote = "1.0.40"
itertools = "*"
